version: '3'
services:

  nginx:
    build: ./nginx
    restart: unless-stopped
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/:/etc/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client
      - server

  client:
    build: ./client
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../srcs/client/:/workspace

  server:
    build: ./server
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../srcs/server/:/workspace
    depends_on:
      - database

  database:
    build: ./database
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Europe/Paris
      - PGTZ=Europe/Paris
    volumes:
      # - ./db:/var/lib/postgresql/data # Uncomment for persistency
      - ../srcs/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports: # Remove to disable connection from outside
      - "5432:5432"
